---
title: "Semi Bernoulli Items"
author: "Ben Ewing and Neil Pruthi"
date: "December 7, 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Setup

R setup.

```{r r-setup, include = FALSE}
# For data manipulation
library(dplyr)
library(purrr)
library(purrr)
# For linear programming
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)
# Minimax
source("../r/n_player_minimax.R")
```

Python/reticulate setup.

```{r py-setup}
library(reticulate)
use_python("C:/ProgamData/Anaconda3/python.exe")
# Load utility functions
source_python("../py/estimate_utility.py")
# and Numpy
np <- import("numpy", convert=FALSE)
```

# Rock Paper Scissors Test

```{r rps}
n_players <- as.integer(2)

items <- np_array(matrix(c(
  c( 0, -1,  1, 
     1,  0, -1, 
     -1,  1,  0)
), ncol = 3, byrow = T))

items_u <- est_knap_u(items, n_players)

minimax(items_u, n_players)$solution
```

# Case 1

```{r case-1}
n_players <- as.integer(3)
m_items <- 4

items <- np_array(matrix(c(
  c(  1,  2,  3,  4,
     -1, -2, -3, -4,
      1,  2,  3,  4,
     -1, -2, -3, -4)
), ncol = m_items, byrow = T))

items_u <- est_knap_u(items, n_players)

minimax(items_u, n_players)$solution
```

Case 1 extended

```{r case-1-ex}
n_players <- as.integer(3)
n_draws <- 1000
m_items <- 5

items <- np_array(matrix(c(
  c(-1, 1)[rbinom(n_draws, 1, 0.5) + 1], 
  c(-2, 2)[rbinom(n_draws, 1, 0.5) + 1],
  c(-3, 3)[rbinom(n_draws, 1, 0.5) + 1],
  c(-4, 4)[rbinom(n_draws, 1, 0.5) + 1],
  c(-20, 20)[rbinom(n_draws, 1, 0.5) + 1]
), ncol = m_items))
np$nanmean(items, axis = as.integer(0))
np$nanvar(items, axis = as.integer(0))

items_u <- est_knap_u(items, n_players)

minimax(items_u, n_players)$solution
```

Case 1 extended more.

```{r case-1-ex-more}
n_players <- as.integer(3)
n_draws <- 1000
m_items <- 5

map_df(seq(5, 25, 3), ~ {
  print(.x)
  items <- sapply(sample(1:.x, size = round(.x/2), replace = F), function(x) c(-x, x)[rbinom(n_draws, 1, 0.5) + 1])
  imean <- np$nanmean(items, axis = as.integer(0))
  ivar <- np$nanvar(items, axis = as.integer(0))
  items_u <- est_knap_u(items, n_players)
  mini <- as.vector(minimax(items_u, n_players)$solution)
  data_frame(
    pr = mini[-length(mini)],
    mean = as.vector(np$nanmean(items, axis = as.integer(0))),
    var = as.vector(np$nanvar(items, axis = as.integer(0))),
    run = .x
  )
})
```
